require("dotenv").config();

const Coche = require("../models/Coche");
const { TIPO_DE_COCHE, COLOR, PUERTAS } = require("../utils/constants");

const coches = [
  {
    marca: "Alfa Romeo",
    modelo: "4C",
    puertas: PUERTAS.DOS,
    tipoDeCoche: TIPO_DE_COCHE.DEPORTIVO,
    potencia: 232,
    oferta: false,
    visible: true,
    vendido: false,
    color: COLOR.BLUE,
  },
  {
    marca: "Aston Martin",
    modelo: "DB5",
    puertas: PUERTAS.DOS,
    tipoDeCoche: TIPO_DE_COCHE.DEPORTIVO,
    potencia: 282,
    oferta: true,
    visible: true,
    vendido: false,
    color: COLOR.RED,
  },
  {
    marca: "Audi",
    modelo: "RS3 Sportback",
    puertas: PUERTAS.CUATRO,
    tipoDeCoche: TIPO_DE_COCHE.DEPORTIVO,
    potencia: 400,
    oferta: false,
    visible: false,
    vendido: true,
    color: COLOR.GREEN,
  },
  {
    marca: "Bugatti",
    modelo: "Veyron 16.4 Super Sport",
    puertas: PUERTAS.DOS,
    tipoDeCoche: TIPO_DE_COCHE.DEPORTIVO,
    potencia: 1200,
    oferta: false,
    visible: false,
    vendido: true,
    color: COLOR.BLUE,
  },
  {
    marca: "Ford",
    modelo: "Fiesta VI",
    puertas: PUERTAS.CUATRO,
    tipoDeCoche: TIPO_DE_COCHE.TURISMO,
    potencia: 125,
    oferta: true,
    visible: true,
    vendido: false,
    color: COLOR.RED,
  },
  {
    marca: "Honda",
    modelo: "CR-V",
    puertas: PUERTAS.CUATRO,
    tipoDeCoche: TIPO_DE_COCHE.TODOTERRENO,
    potencia: 212,
    oferta: false,
    visible: true,
    vendido: false,
    color: COLOR.RED,
  },
  {
    marca: "Mercedes-Benz",
    modelo: "CLA 180",
    puertas: PUERTAS.CUATRO,
    tipoDeCoche: TIPO_DE_COCHE.TURISMO,
    potencia: 116,
    oferta: false,
    visible: false,
    vendido: true,
    color: COLOR.BLUE,
  },
  {
    marca: "Nissan",
    modelo: "X-Trail",
    puertas: PUERTAS.CUATRO,
    tipoDeCoche: TIPO_DE_COCHE.TODOTERRENO,
    potencia: 136,
    oferta: true,
    visible: true,
    vendido: false,
    color: COLOR.GREEN,
  },
  {
    marca: "Peugeot",
    modelo: "RCZ",
    puertas: PUERTAS.DOS,
    tipoDeCoche: TIPO_DE_COCHE.DEPORTIVO,
    potencia: 163,
    oferta: false,
    visible: true,
    vendido: false,
    color: COLOR.GREY,
  },
  {
    marca: "Seat",
    modelo: "Ibiza V",
    puertas: PUERTAS.CUATRO,
    tipoDeCoche: TIPO_DE_COCHE.TURISMO,
    potencia: 150,
    oferta: false,
    visible: false,
    vendido: true,
    color: COLOR.BLACK,
  },
];

Coche.bulkCreate(coches).then(() => console.log("Your cars are loaded 🚗"));
